# Install NGINX web server

- name: Update apt package cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install NGINX package
  apt:
    name: "{{ nginx_package }}"
    state: present
