$ANSIBLE_VAULT;1.1;AES256
38643830626161303962623037656563656639346432343232336163613833666264386432326363
6337393763376365343735663565656336323032636336650a626266326163623833613931386333
34666231666134646661343761363064643933656464323164616439366265343332323164383335
3934613665623864300a363636353630636532333861633163363265656333376634616261353739
30346665623939376162343838343864393362666436396338363837386535646333663839623366
37306365663135663931343133626564316661393332333532373434346634643939323764333337
65363136376635653163353865396666353330336432356430383531376431613964326464663432
36346230373665346236
